#!/bin/bash

clear

font="noto-fonts-cjk noto-fonts-emoji noto-fonts ttf-jetbrains-mono-nerd ttf-roboto-mono-nerd ttf-roboto-mono"
package="neovim-nightly-bin ripgrep fzf zoxide lazygit eza zsh ibus ibus-bamboo ranger hyprshot swaybg hyprland sddm pamixer gd rofi-emoji xdotool pacman-contrib trizen"
applications="firefox google-chrome visual-studio-code-bin neovide discord spotify spicetify-cli"

PS3="Enter a number: "
options=("Install Paru" "Install Fonts" "Install Package" "Install ZAP" "Install Applications" "Setup" "Quit")

select opt in "${options[@]}"
do
  clear
  case $opt in
    "Install Paru")
      if [ $(command -v git) ]; then
        git clone https://aur.archlinux.org/paru.git $HOME/.cache/paru-git
        cd $HOME/.cache/paru-git
        makepkg -si
        rm -rf $HOME/.cache/paru-git/
      else
        echo "Please install Git first!"
      fi
      ;;
    "Install Fonts")
      paru -S $font
      ;;
    "Install Package")
      paru -S $package
      ;;
    "Install ZAP")
      zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) -k
      ;;
    "Install Applications")
      paru -S $applications
      ;;
    "Setup")
      sudo systemctl enable sddm
      ;;
    "Quit")
      break
      ;;
    *) echo "Wrong option!"
  esac

  read -p "Press Enter to continue..."
  clear
done
