alias nv='nvim'
alias lv='lvim'
alias ll='colorls -lA --sd --group-directories-first'
alias ls='colorls --group-directories-first'
alias glst='git log -1 HEAD'
alias live='live-server'
alias xrn='xrandr --newmode'
alias xra='xrandr --addmode VGA-1'
